In [1]:
import numpy as np
arr=np.array([1 , 2 , 3],  dtype =np.int32 )
print(arr)

[1 2 3]


In [2]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
sum_arr=arr1+arr2
print(sum_arr)

[ 7  9 11 13 15]


In [4]:
sum_array=np.sum(arr1)
print(sum_array)

15


In [6]:
mean_arry=np.mean(arr1)
print(mean_arry)

3.0


In [9]:
two_array=np.array([[1,2,3],[4,5,6]])
reshaped_array=two_array.reshape((3,2))
print(two_array)

[[1 2 3]
 [4 5 6]]


In [10]:
arr3=np.array([1,2,3])
arr4=np.array([[4],[5],[6]])
brodcast_array=arr3+arr4
print(brodcast_array)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [14]:
arr=np. array([1 , 2 , 3 , 4 , 5])
bool_idx=arr>3
filtered_arr=arr[bool_idx]
print(filtered_arr)

[4 5]


In [17]:
arr5=np.array([1,2,3,4,5,6,7,8,9])
print(np. percentile ( arr5 ,  50))
print(np. quantile ( arr5 ,  0.25))
print(arr5)

5.0
3.0
[1 2 3 4 5 6 7 8 9]


In [21]:
arr1  =  np. array ([1 ,  2 ,  3])
arr2  =  np. array ([4 ,  5 ,  6])
correlation  =  np. corrcoef( arr1 ,  arr2 )
print(correlation)
print()
print(np. cov( arr1 ,  arr2 ))

[[1. 1.]
 [1. 1.]]

[[1. 1.]
 [1. 1.]]
