In [1]:
#Task 1

In [2]:
import numpy as np
n = np.arange(1, 21)        
arr = n**2 + 1                
matrix = arr.reshape(4, 5)   
print(matrix)

[[  2   5  10  17  26]
 [ 37  50  65  82 101]
 [122 145 170 197 226]
 [257 290 325 362 401]]


In [3]:
double_matrix = matrix * 2
print(double_matrix)

[[  4  10  20  34  52]
 [ 74 100 130 164 202]
 [244 290 340 394 452]
 [514 580 650 724 802]]


In [4]:
modified_matrix = matrix.copy()
modified_matrix[modified_matrix% 5 == 0] = -1
print(modified_matrix)

[[  2  -1  -1  17  26]
 [ 37  -1  -1  82 101]
 [122  -1  -1 197 226]
 [257  -1  -1 362 401]]


In [5]:
count_replaced = np.sum(matrix % 5 == 0)
print("Numbers replaced:", count_replaced)

Numbers replaced: 8


In [6]:
#Task 2

In [7]:
import numpy as np
A = np.arange(1, 101).reshape(10, 10)
prime_rows = A[[1, 2, 4, 6], :]
print(prime_rows)

[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [41 42 43 44 45 46 47 48 49 50]
 [61 62 63 64 65 66 67 68 69 70]]


In [8]:
B = A.copy()
B[:, ::2] = B[::-1, ::2]   # reverse columns at even indices (0,2,4,…)
print(B)

[[ 91   2  93   4  95   6  97   8  99  10]
 [ 81  12  83  14  85  16  87  18  89  20]
 [ 71  22  73  24  75  26  77  28  79  30]
 [ 61  32  63  34  65  36  67  38  69  40]
 [ 51  42  53  44  55  46  57  48  59  50]
 [ 41  52  43  54  45  56  47  58  49  60]
 [ 31  62  33  64  35  66  37  68  39  70]
 [ 21  72  23  74  25  76  27  78  29  80]
 [ 11  82  13  84  15  86  17  88  19  90]
 [  1  92   3  94   5  96   7  98   9 100]]


In [9]:
C = A.copy()
np.fill_diagonal(C, 0)
print(C)

[[ 0  2  3  4  5  6  7  8  9 10]
 [11  0 13 14 15 16 17 18 19 20]
 [21 22  0 24 25 26 27 28 29 30]
 [31 32 33  0 35 36 37 38 39 40]
 [41 42 43 44  0 46 47 48 49 50]
 [51 52 53 54 55  0 57 58 59 60]
 [61 62 63 64 65 66  0 68 69 70]
 [71 72 73 74 75 76 77  0 79 80]
 [81 82 83 84 85 86 87 88  0 90]
 [91 92 93 94 95 96 97 98 99  0]]


In [10]:
border_sum = (
    np.sum(A[0, :]) + np.sum(A[-1, :]) +   # top + bottom rows
    np.sum(A[1:-1, 0]) + np.sum(A[1:-1, -1])  # left + right columns (excluding corners)
)
print("Border sum:", border_sum)

Border sum: 1818


In [11]:
rotated = np.rot90(A, -1)   # -1 → clockwise
print(rotated)

[[ 91  81  71  61  51  41  31  21  11   1]
 [ 92  82  72  62  52  42  32  22  12   2]
 [ 93  83  73  63  53  43  33  23  13   3]
 [ 94  84  74  64  54  44  34  24  14   4]
 [ 95  85  75  65  55  45  35  25  15   5]
 [ 96  86  76  66  56  46  36  26  16   6]
 [ 97  87  77  67  57  47  37  27  17   7]
 [ 98  88  78  68  58  48  38  28  18   8]
 [ 99  89  79  69  59  49  39  29  19   9]
 [100  90  80  70  60  50  40  30  20  10]]


In [12]:
#Task 3

In [13]:
arr = np.random.randint(1, 501, size=1000)
perfect_squares = np.sum(np.sqrt(arr).astype(int)**2 == arr)
print("Perfect squares:", perfect_squares)

Perfect squares: 47


In [14]:
from sympy import isprime

prime_count = np.sum([isprime(x) for x in arr])
print("Prime numbers:", prime_count)

Prime numbers: 194


In [15]:
arr_mod = arr.copy()
arr_mod[arr_mod % 7 == 0] = np.sqrt(arr_mod[arr_mod % 7 == 0])

In [16]:
sorted_arr = np.sort(arr)
largest_gap = np.max(np.diff(sorted_arr))
print("Largest gap:", largest_gap)

Largest gap: 4


In [17]:
cumsum = np.cumsum(arr)
index_exceed = np.argmax(cumsum > 100000)   # first index where condition is True
print("First index exceeding 100000:", index_exceed)

First index exceeding 100000: 393


In [18]:
#Task 4

In [19]:
import numpy as np

# Random patient counts between 50–250
data = np.random.randint(50, 251, size=(30, 5))
print(data.shape)   # (30,5)

(30, 5)


In [23]:
mean_dept = np.mean(data, axis=0)
print("Department-wise Mean:", mean_dept)

Department-wise Mean: [165.66666667 136.53333333 158.73333333 135.         154.43333333]


In [24]:
median_dept = np.median(data, axis=0)
print("Department-wise Median:", median_dept)

Department-wise Median: [153.5 122.5 167.  123.5 165. ]


In [25]:
std_dept = np.std(data, axis=0)
print("Department-wise Std Dev:", std_dept)

Department-wise Std Dev: [55.34578173 56.60255196 47.25387697 55.29496662 49.56254186]


In [26]:
highest_day = np.max(data, axis=0)
print("Highest Patient Day:", highest_day)

Highest Patient Day: [248 230 229 235 230]


In [27]:
lowest_day = np.min(data, axis=0)
print("Lowest Patient Day:", lowest_day)

Lowest Patient Day: [67 51 75 54 63]


In [28]:
# Calculate thresholds
upper = mean_dept + 2*std_dept
lower = mean_dept - 2*std_dept

# Boolean mask for outliers
outliers = (data < lower) | (data > upper)
print("Outliers detected:\n", outliers)

Outliers detected:
 [[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False Fal

In [29]:
# Copy data to avoid overwriting
cleaned_data = data.copy()

for dept in range(data.shape[1]):
    cleaned_data[outliers[:, dept], dept] = mean_dept[dept]

print("Cleaned Data:\n", cleaned_data)

Cleaned Data:
 [[222 230 204 115 108]
 [153 105 176  54 215]
 [136 201 207 160  94]
 [ 82 147 204  80 230]
 [239 188 150  76 119]
 [ 74 117 195 165 212]
 [248 128 190 102 179]
 [228  93 121 105 162]
 [113  67 223  68 122]
 [222 218 215 158  91]
 [107  56 111 114 153]
 [154  66 150 174 224]
 [190 202  77 177 176]
 [127  75 183 235 168]
 [224 214 229  67 172]
 [ 67 176  75 230 210]
 [224 213 191 144  67]
 [232 168 141 155 200]
 [210 207 128 233 112]
 [141  79 158 191  86]
 [152  51 177 168 181]
 [227 128 195 210  63]
 [141 114  80  65 125]
 [127  91 139  63 126]
 [202 165  86 112 175]
 [150 207  84  87 170]
 [ 81 112 144 114 100]
 [101  63 122  82 152]
 [193 109 186 214 222]
 [203 106 221 132 219]]
